In [17]:
import torch

In [18]:
if torch.cuda.is_available():
  print('GPU is find')
  print(f'GPU capabilit : {torch.cuda.get_device_capability()}')
  print(f'GPU name : {torch.cuda.get_device_name()}')
else:
  print('GPU is not find')

GPU is find
GPU capabilit : (7, 5)
GPU name : Tesla T4


## tensor

In [19]:
a=torch.empty(3,3)
a

tensor([[4.0278e+03, 4.4654e-41, 4.8025e-11],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [20]:
type(a)

torch.Tensor

In [21]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.rand(3,3)

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [24]:
# manual seed
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [25]:
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [26]:
# torch tensor (for custom tensor)
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

# tensor shape using python method

In [27]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
a.shape

torch.Size([2, 3])

In [29]:
## to make same dim tensor
torch.empty_like(a)


tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 4062922188999713840]])

In [30]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
## same for ones
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
# but with rand there is problem and to solve it we need to first understand the tensor
#datatype and how we can chnage it
#torch.rand_like(a)

# tensor data type

In [33]:
a.dtype

torch.int64

In [34]:
b = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.int32)
b


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [35]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
# and we can also convert existing tensor datatype
a.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [37]:
# so the solution of rand is
torch.rand_like(a,dtype=torch.float64)

tensor([[0.9443, 0.8848, 0.3006],
        [0.2113, 0.0521, 0.4188]], dtype=torch.float64)

# mathmetical operation on tensor

## 1. scaler operations

In [38]:
x = torch.rand(2,2)
x

tensor([[0.8238, 0.5557],
        [0.9770, 0.4440]])

In [39]:
# add
x + 2

tensor([[2.8238, 2.5557],
        [2.9770, 2.4440]])

In [40]:
# sub
x-2

tensor([[-1.1762, -1.4443],
        [-1.0230, -1.5560]])

In [41]:
x*2

tensor([[1.6477, 1.1115],
        [1.9540, 0.8880]])

In [42]:
x/3

tensor([[0.2746, 0.1852],
        [0.3257, 0.1480]])

In [43]:
# int div
ans = (x * 100) // 3
ans

tensor([[27., 18.],
        [32., 14.]])

In [44]:
# mod
ans %2

tensor([[1., 0.],
        [0., 0.]])

In [45]:
# power
ans ** 2

tensor([[ 729.,  324.],
        [1024.,  196.]])

# Element wise operation (operation b/w two tensor)

In [46]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277]])
tensor([[0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535]])


In [47]:
a + b

tensor([[1.1950, 1.5354, 0.9127],
        [0.2595, 0.9212, 1.4812]])

In [48]:
a - b

tensor([[ 0.7007, -0.0464,  0.0657],
        [ 0.2257,  0.4794, -0.4258]])

In [49]:
a / b

tensor([[ 3.8346,  0.9413,  1.1552],
        [14.3533,  3.1705,  0.5534]])

In [50]:
a ** b

tensor([[0.9868, 0.7919, 0.7388],
        [0.9763, 0.9243, 0.5436]])

# we can also do some more opertion on single tensor like..

In [51]:
c = torch.tensor([-1,3,-5,7])
c

tensor([-1,  3, -5,  7])

In [52]:
torch.abs(c)

tensor([1, 3, 5, 7])

In [53]:
torch.neg(c)

tensor([ 1, -3,  5, -7])

In [54]:
d = torch.tensor([1.4,2.1,4.6])

In [55]:
# round
torch.round(d)

tensor([1., 2., 5.])

In [56]:
# ceil
torch.ceil(d)

tensor([2., 3., 5.])

In [57]:
# floor
torch.floor(d)

tensor([1., 2., 4.])

In [58]:
# clamp
torch.clamp(d,min=-1,max=4)

tensor([1.4000, 2.1000, 4.0000])

## Reduction opration

In [59]:
e = torch.randint(size=(2,3),low=0,high=100,dtype=torch.float32)
e

tensor([[39., 64., 20.],
        [55.,  7., 15.]])

In [60]:
torch.sum(e)

tensor(200.)

In [61]:
# colum wise
torch.sum(e,dim=0)

tensor([94., 71., 35.])

In [62]:
# raw wise sum
torch.sum(e,dim=1)


tensor([123.,  77.])

In [63]:
torch.mean(e)

tensor(33.3333)

In [64]:
# mean for col
torch.mean(e,dim=0)

tensor([47.0000, 35.5000, 17.5000])

In [65]:
# mean for raw
torch.mean(e,dim=1)

tensor([41.0000, 25.6667])

In [66]:
torch.median(e)

tensor(20.)

In [67]:
torch.max(e)

tensor(64.)

In [68]:
torch.min(e)

tensor(7.)

In [69]:
torch.prod(e)

tensor(2.8829e+08)

In [70]:
torch.std(e)

tensor(23.0188)

In [71]:
torch.var(e)

tensor(529.8666)

In [72]:
torch.argmax(e)

tensor(1)

# Matrix Operations

In [73]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)


tensor([[9, 9, 7],
        [5, 9, 8]])
tensor([[9, 7],
        [9, 2],
        [6, 7]])


In [74]:
# multi
torch.matmul(f,g)

tensor([[204, 130],
        [174, 109]])

In [75]:
# and also do the dot prod
ab = torch.tensor([2,4])
cd = torch.tensor([2,1])
torch.dot(ab,cd)


tensor(8)

In [76]:
# transpose
torch.transpose(f,0,1)

tensor([[9, 5],
        [9, 9],
        [7, 8]])

In [77]:
## also determinet  (raw == col) Sqr matrix
A = torch.tensor([[9,3],[5,3]],dtype = torch.float32)
torch.det(A)


tensor(12.0000)

In [78]:
torch.inverse(A)

tensor([[ 0.2500, -0.2500],
        [-0.4167,  0.7500]])

## compare opertion

In [79]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

In [80]:
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [81]:
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [82]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [83]:
i !=j

tensor([[True, True, True],
        [True, True, True]])

## Special functions

like in some operation we need tensor in float for coumputaion


In [84]:
k = torch.randint(size=(2,3),low=1,high=10,dtype = torch.float32)
k

tensor([[6., 5., 1.],
        [1., 3., 1.]])

In [85]:
torch.log(k)

tensor([[1.7918, 1.6094, 0.0000],
        [0.0000, 1.0986, 0.0000]])

In [86]:
torch.sqrt(k)

tensor([[2.4495, 2.2361, 1.0000],
        [1.0000, 1.7321, 1.0000]])

In [87]:
torch.exp(k)

tensor([[403.4288, 148.4132,   2.7183],
        [  2.7183,  20.0855,   2.7183]])

# import for deep learing.

In [88]:
# imp in nn
torch.sigmoid(k)

tensor([[0.9975, 0.9933, 0.7311],
        [0.7311, 0.9526, 0.7311]])

In [89]:
# softmax ko dim ki need hai becu we need to cal the porb
torch.softmax(k,dim = 0)

tensor([[0.9933, 0.8808, 0.5000],
        [0.0067, 0.1192, 0.5000]])

In [90]:
## Relu
torch.relu(k)

tensor([[6., 5., 1.],
        [1., 3., 1.]])

# implace opration

In [91]:
m = torch.randint(size=(2,3),low=0,high=10)
n = torch.randint(size=(2,3),low=0,high=10)
print(m)
print(n)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


So it need more memeory to store the result tensor

In [92]:
m + n

tensor([[ 8, 13, 10],
        [ 9, 11,  8]])

In [93]:
# and it create so much problem in space merory in dl
# so what we do
m.add_(n)

tensor([[ 8, 13, 10],
        [ 9, 11,  8]])

## so here we use merory of m to store the result of m + n

In [94]:
m

tensor([[ 8, 13, 10],
        [ 9, 11,  8]])

In [95]:
# one more ex
torch.relu(m)
# so it need another space to store it so what we do we implace it by its self

tensor([[ 8, 13, 10],
        [ 9, 11,  8]])

In [96]:
m.relu_()

tensor([[ 8, 13, 10],
        [ 9, 11,  8]])

## copying a Tensor

In [97]:
a = torch.rand(3,3)



In [98]:
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [99]:
b = a

In [100]:
id(b)

136858774255040

In [101]:
id(a)

136858774255040

In [102]:
c = a.clone()

In [103]:
c

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [104]:
id(c)

136858774275088

# Tensor Opration on GPU

In [105]:
torch.cuda.is_available()

True

In [106]:
device = torch.device('cuda')

In [107]:
torch.rand((2,2),device=device)

tensor([[0.3563, 0.0303],
        [0.7088, 0.2009]], device='cuda:0')

In [108]:
a = torch.rand((2,2))
a.to(device)

tensor([[0.1780, 0.3011],
        [0.1893, 0.9186]], device='cuda:0')

# here we compare it 

In [1]:
import torch

In [4]:
import time

size = 11000
matrix1_cpu =  torch.randn(size,size)
matrix2_cpu = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix1_cpu,matrix2_cpu) 
cpu_time = time.time() - start_time

# move tensor to gpu

matrix1_gpu = matrix1_cpu.to('cuda')
matrix2_gpu = matrix2_cpu.to('cuda')


# using gpu 

start_time = time.time()

result_gpu = torch.matmul(matrix1_gpu,matrix2_gpu)
torch.cuda.synchronize()
gpu_time = time.time() - start_time


print(f'time taken by cpu {cpu_time}')
print(f'time taken by GPU : {gpu_time}')






time taken by cpu 11.814161777496338
time taken by GPU : 0.7369945049285889
